- cas/cas.properties
- ldapadmin/templates/newaccount-requires-moderation-template.txt
See https://github.com/georchestra/georchestra/issues/1107
> PENDING_USERS renamed

- geonetwork/config/config-datadir-georchestra.xml
- geonetwork/config/config-overrides-georchestra.xml
- geonetwork/geonetwork.properties
Backport of @landryb's PR, see
https://github.com/georchestra/geonetwork/pull/26
> GN - allow configuring data-subdirectories

- cas/cas.properties
- extractorapp/extractorapp.properties
- extractorapp/js/GEOR_custom.js
- extractorapp/templates/extractor-email-ack-template.tpl
- extractorapp/templates/extractor-email-template.tpl
- geowebcache/geowebcache.properties
- ldapadmin/templates/changepassword-email-template.txt
- mapfishapp/js/GEOR_custom.js
- mapfishapp/print/config.yaml
- mapfishapp/wfs.servers.json
- mapfishapp/wms.servers.json
- mapfishapp/wmts.servers.json
- security-proxy/security-proxy.properties
Proposal for https://github.com/georchestra/georchestra/issues/1123
BTW: sdi.georchestra.org as well ...
> Switch to SSL by default

- mapfishapp/addons/annotation/config.json
- mapfishapp/addons/cadastre/config.json
- mapfishapp/addons/extractor/config.json
- mapfishapp/addons/fullscreen/config.json
- mapfishapp/addons/locateme/config.json
- mapfishapp/addons/magnifier/config.json
- mapfishapp/addons/measure/config.json
- mapfishapp/addons/openls/config.json
- mapfishapp/addons/osm2geor/config.json
- mapfishapp/addons/quicksearch/config.json
- mapfishapp/addons/streetview/config.json
This way, administrators can directly configure/override the
addons they want to use.
> Add a copy of config.json files in the datadir

- security-proxy/user-agents.properties
Related issue:
https://github.com/georchestra/georchestra/pull/1267
> SP - removing UA for extractorapp

- geonetwork/config/config-db-georchestra.xml
- geonetwork/geonetwork.properties
Runtime tests: into a docker composition, following the workflow described below:
> Trying to put a custom dialect / schema for GN

- mapfishapp/addons/measurements/config.json
Related to https://github.com/georchestra/georchestra/pull/1309
> advanced measurements addon

- cas/cas.properties
- geonetwork/geonetwork.properties
- ldapadmin/ldapadmin.properties
- security-proxy/security-proxy.properties
See https://github.com/georchestra/georchestra/issues/1415
> groups renamed into roles

- geonetwork/geonetwork.properties
- ldapadmin/protectedgroups.properties
- mapfishapp/addons/cadastre/config.json
- mapfishapp/js/GEOR_custom.js
- security-proxy/security-mappings.xml
see https://github.com/georchestra/georchestra/issues/1428
> LDAP groups SV_ renamed

- ldapadmin/ldapadmin.properties
- security-proxy/security-proxy.properties
Add new values for 'requiredFields' : "orgShortName", "orgAddress" and
"orgType".
Add configuration parameter : 'orgTypeValues' for allowed value of
organization types.
> Add configuration for organization

- cadastrapp/cadastrapp.properties
- cadastrapp/jetty-env.xml
- cadastrapp/logback.xml
Following https://github.com/georchestra/datadir/pull/23#issuecomment-243410408
> cadastrapp - adding default datadir files

- atlas/mapfishprintv3/A3_Landscape.jrxml
- atlas/mapfishprintv3/A3_Portrait.jrxml
- atlas/mapfishprintv3/A4_Landscape.jrxml
- atlas/mapfishprintv3/A4_Portrait.jrxml
- atlas/mapfishprintv3/config.yaml
Will require a modification onto the atlas (see CamelMapfishPrintComponent.java) to be used.
> atlas - adding config.yaml + jasper templates

- security-proxy/security-proxy.properties
PR for https://github.com/georchestra/georchestra/issues/1153
> proxy - remove healthcheck

- mapfishapp/mapfishapp.properties
Linked with : https://github.com/georchestra/georchestra/pull/1602
> mapfishapp - fix path to 'uploads' folder

- ldapadmin/ldapadmin.properties
This addresses both:
* https://github.com/georchestra/georchestra/issues/1592
* https://github.com/georchestra/georchestra/issues/1591 (partially)
* https://github.com/georchestra/georchestra/issues/1576
* https://github.com/georchestra/datadir/issues/43
> ldapadmin properties revamped for 16.12

- analytics/analytics.properties
This PR add configuration in datadir for : https://github.com/georchestra/georchestra/pull/1626
> analytics - add configuration to filter system users on stats

- mapfishapp/wfs.servers.json
should be useful for everyone.
> Adding the local WFS geoserver

- security-proxy/security-proxy.properties
Configuration part of https://github.com/georchestra/georchestra/pull/1674
> [WIP] Proxy trust another proxy

- console/console.properties
- console/log4j/log4j.properties
- console/protectedroles.properties
- console/templates/newaccount-requires-moderation-template.txt
with https://github.com/georchestra/georchestra/issues/1431
> rename groups into roles

- cadastrapp/cadastrapp.properties
- cas/cas.properties
- console/protectedroles.properties
- geonetwork/config/config-security-georchestra.xml
- geonetwork/geonetwork.properties
- security-proxy/security-proxy.properties
companion PR for https://github.com/georchestra/georchestra/pull/1918
> gn / sp / cas properties renamed groups -> roles

- console/console.properties
And adapt `AreasKey`, `AreasKey` and `AreasGroup`
> Enable auto center/zoom in console

- atlas/atlas.properties
- cas/cas.properties
- console/templates/account-creation-in-progress-template.txt
- console/templates/account-uid-renamed.txt
- console/templates/changepassword-email-template.txt
- console/templates/newaccount-requires-moderation-template.txt
- console/templates/newaccount-was-created-template.txt
- default.properties
- extractorapp/extractorapp.properties
- extractorapp/templates/extractor-email-ack-template.tpl
- extractorapp/templates/extractor-email-template.tpl
- geowebcache/geowebcache.properties
- security-proxy/security-proxy.properties
and remove occurrence of public URL "georchestra.mydomain.org" in webapps configuration.
Done in : 
* extractorapp
* console
> Add default.properties to store public URL

- security-proxy/security-mappings.xml
* MOD_EXTRACTORAPP was renamed into EXTRACTORAPP
* MOD_ANALYTICS was removed
* MOD_EMAILPROXY should be renamed into EMAILPROXY
> double check proxy security-mappings for 18.06

- geonetwork/config/config-security-georchestra.xml
See https://github.com/georchestra/georchestra/issues/1258
> GN - configure a redirection to /cas/login when relevant

- geonetwork/config/config-security-georchestra.xml
See https://github.com/georchestra/georchestra/issues/1258#issuecomment-399429157
> GN - using the regular spring class for login entrypoint

- console/console.properties
Encoding was changed by this commit :
06ff380168e2c2e125c38b4061d349eaef801d25
> Fix encoding of console.properties

- console/console.properties
- console/templates/newaccount-notification-template.txt
and add templateEncoding parameter and a new mail template
> Remove moderatorEmail and language parameter

- console/console.properties
see https://github.com/georchestra/georchestra/pull/2239
> console - add possibility to disable recaptcha

- mapfishapp/addons/goto/config.json
Fixes https://github.com/georchestra/georchestra/issues/2257.
To be merged after https://github.com/georchestra/georchestra/pull/2325.
> viewer - localize two fields in Goto addon

- mapfishapp/addons/coordinates/config.json
Fixes https://github.com/georchestra/georchestra/issues/2326.
To be merged after https://github.com/georchestra/georchestra/pull/2327.
>  viewer - localize two fields in Coordinates addon

- geonetwork/log4j/log4j.xml
Code by https://github.com/landryb, see:
https://github.com/georchestra/georchestra/issues/1850#issuecomment-416949322
> fixes #85 - use a dedicated directory for harvester logs in geonetwork

- analytics/analytics.properties
- cas/cas.properties
- console/console.properties
- default.properties
- geowebcache/geowebcache.properties
- mapfishapp/mapfishapp.properties
See https://github.com/georchestra/georchestra/pull/2367
> Change instance name property name

- mapfishapp/js/GEOR_custom.js
See https://github.com/georchestra/georchestra/pull/2381
> viewer - remove support for OpenAddresses

- console/templates/account-creation-in-progress-template.txt
- console/templates/account-uid-renamed.txt
- console/templates/changepassword-email-template.txt
- console/templates/newaccount-notification-template.txt
- console/templates/newaccount-requires-moderation-template.txt
- console/templates/newaccount-was-created-template.txt
- extractorapp/templates/extractor-email-ack-template.tpl
- extractorapp/templates/extractor-email-template.tpl
in extractorapp and console modules
> Use instanceName instead of hardcoded geOrchestra

- console/console.properties
Missing properties after https://github.com/georchestra/georchestra/pull/2184
> console - add missing properties for pending ou

- console/console.properties
goes with georchestra/georchestra#2162
> default readonlyUid to false (georchestra/georchestra#2104)

- console/templates/newaccount-requires-moderation-template.txt
relates to https://github.com/georchestra/georchestra/pull/2408.
> mail template has to target 'new' pending users services

- geowebcache/geowebcache.properties
See https://github.com/georchestra/georchestra/issues/2555 and
https://github.com/georchestra/georchestra/pull/2560/commits/41961de98c05f83476c386bbd017d9dde86d3ba1
> gwc - configure the configuration file directory

- geowebcache/geowebcache.properties
Requires gwc dockerfile update ... to come
> Introducing geowebcache datadir

- console/protectedroles.properties
Goes along with https://github.com/georchestra/georchestra/issues/2147
> Protect role REFERENT

- geonetwork/geonetwork.properties
follow https://github.com/georchestra/datadir/pull/168
> gn, sync group with ldap, use cn at this place also

- console/templates/newaccount-notification-template.txt
- console/templates/newaccount-requires-moderation-template.txt
need https://github.com/georchestra/georchestra/pull/2722 to work properly
> add org to new users template

- mapstore/localConfig.json
Added a missing file for mapstore configuration as discussed here: https://github.com/georchestra/mapstore2-georchestra/issues/169
> Added mapstore client main configuration file

- console/console.properties
See https://github.com/georchestra/georchestra/pull/3119 for the motivation
> Console - add SASL options

- console/console.properties
See https://github.com/georchestra/georchestra/pull/2806
> console - add an option for toggling gdpr

- README.md
- default.properties
- mapfishapp/credentials.properties
- mapfishapp/js/GEOR_custom.js
- mapfishapp/print/config.yaml
- mapfishapp/wfs.servers.json
- mapfishapp/wms.servers.json
- mapfishapp/wmts.servers.json
- mapstore/printing/config.yaml
See https://github.com/georchestra/docker/pull/92
> Using traefik.me fqdn for the docker composition

- datafeeder/metadata_template.xml
Update metadata template to be INSPIRE compliant
See https://github.com/inspire-eu-validation/metadata/blob/2.0/common/conditions-for-access-and-use.md
> [datafeeder]: INSPIRE compliance

- mapstore/localConfig.json
Thanking @landryb for the heads up on #213 
Now how far should this one be backported ? ...
> mapstore - update localConfig.json

- security-proxy/headers-mapping.properties
- security-proxy/security-mappings.xml
* sending json representation as http header to gn & datafeeder
* protecting new console webservices for internal use / superuser only
> SP - missing bits from previous PR #215

- geonetwork/microservices/searching/gn-cloud-searching-application.yml
followup to georchestra/ansible#90
> add template for gn-cloud-searching application

- cas/config/cas.properties
> cas - disable default cas fixed credential list

- mapstore/configs/localConfig.json
> [mapstore] update localConfig.json

- mapstore/configs/newgeostory.json
> #245 add newgeostory file

- datafeeder/frontend-config.json
fix thesaurus name ? to be backported onto 22.0 ?
> [datafeeder] align with georchestra/ansible@3731520

- geonetwork/geonetwork.properties
> Get rid of geonetwork user

- mapstore/configs/README.md
...with a first note regarding WMTS printing
> Mapstore: Add readme for config

- atlas/atlas.properties
- console/console.properties
- datafeeder/datafeeder.properties
- datafeeder/templates/analysis-started-email-template.txt
- default.properties
- security-proxy/security-proxy.properties
> get rid of scheme - https by default

- geonetwork/microservices/ogc-api-records/config.yml
Inspired by the work done on Géo2france.
> Add default config for ogc-api-records microservice

- console/console.properties
PR for GIP https://github.com/georchestra/improvement-proposals/issues/2
[Link to Georchestra PR#3899](https://github.com/georchestra/georchestra/pull/3899)
> Added configurable password requirements

- geonetwork/microservices/ogc-api-records/config.yml
Wondering about the `rabbitmq.host: localhost` line, cc @jahow
> Port of the ogc-api-records service config to the docker setup

- security-proxy/targets-mapping.properties
this is connected with : https://github.com/georchestra/docker/pull/172
> Add ogc api to security-proxy

- geoserver/jetty-env.xml
See https://github.com/georchestra/georchestra/issues/3905#issuecomment-1465808524
> gs - jetty-env - sets accessToUnderlyingResources to true

- README.md
- analytics/analytics.properties
- console/console.properties
- datafeeder/datafeeder.properties
- security-proxy/security-proxy.properties
ref: https://github.com/georchestra/georchestra/pull/3946
> renaming geoserver_privileged_user to georchestra_privileged_user

- datafeeder/datafeeder.properties
ref: https://github.com/georchestra/datadir/pull/293
forgot some modifications
> modify datafeeder configuration

- mapstore/configs/localConfig.json
See https://github.com/georchestra/georchestra/issues/3821
> mapstore - remove cookie warning

- README.md
- analytics/analytics.properties
- console/console.properties
- datafeeder/datafeeder.properties
- security-proxy/security-proxy.properties
Reverts georchestra/datadir#293
> Revert "renaming geoserver_privileged_user to georchestra_privileged_user"

- datafeeder/datafeeder.properties
switching the user used by datafeeder to push data on geonetwork and geoserver
> Datafeeder config user

- gateway/security.yaml
disable by default oauth 2 
connected with : https://github.com/georchestra/georchestra-gateway/pull/33
> disable oauth 2 by default

- geonetwork/geonetwork.properties
ref: https://github.com/georchestra/georchestra/issues/3960
https://github.com/georchestra/docker/issues/201
> Update gn config to use es_port and kb_port

- gateway/gateway.yaml
- gateway/routes.yaml
Backport of https://github.com/georchestra/datadir/pull/299
> Adaptations to the gateway config for docker

- geonetwork/log4j/log4j.xml
> geonetwork - remove fileAppender

- gateway/gateway.yaml
Access to datafeeder and import has to be restricted to SUPERUSER and DATAFEEDER users.
> Restricted access to datafeeder and import

- mapstore/configs/localConfig.json
> backport geopf urls addition

- gateway/application.yaml
- gateway/gateway.yaml
update gateway config with default configuration present here : https://github.com/georchestra/georchestra-gateway/blob/main/gateway/src/main/resources/application.yml#L92
> update gateway config

- datahub/README.md
- datahub/scripts/add-header-webcomponent.sh
- datahub/scripts/add-header.sh
wrong header for the two script of datahub to add header
> update script for datahub add header

- console/templates/newaccount-notification-template.txt
- default.properties
- gateway/security.yaml
On this PR, we add new template to be sent to admin users when new OAuth2 account is created
> Rabbitmq support - spring rabbitmq events console and gateway

- console/templates/newaccount-notification-template.txt
- default.properties
- gateway/security.yaml
Add the changes done in https://github.com/georchestra/datadir/pull/320
> RabbitMQ support - spring rabbitmq events

- default.properties
Remove any usage for the environments variables in the master branch.
Instead set normal values.
> don't use envs for now for master branch

- geoserver/jetty-env.xml
This need to wait for env var configuration in helm chart and docker deployments
connected with  https://github.com/georchestra/geoserver_minimal_datadir/pull/18
> add in jetty-env gs gwc config

- datafeeder/datafeeder.properties
PR resolving this issue : https://github.com/georchestra/datadir/issues/338
need to be ported as well in  branches  docker-master, 23.0 and docker-23.0
> change a comment in datafeeder properties

- default.properties
Add enableRabbitmqEvents prop to default props file
> Add enableRabbitmqEvents prop to default props file

- datafeeder/metadata_template.xml
- datafeeder/metadata_transform.xsl
Also remove irrelevant `aggregationInfo`
> datafeeder - remove references to EEA & geocat

- datafeeder/metadata_template.xml
- datafeeder/metadata_transform.xsl
Same as #351 for docker-master
> Datafeeder - clean template

- console/console.properties
- default.properties
Cherry pick of documentation commit. 
PR on docker-master branch : https://github.com/georchestra/datadir/pull/352
Make analytics and extractor panels configurable with datadir
PR on Georchestra : https://github.com/georchestra/georchestra/pull/4080
> Adds documentation to datadir

- datahub/scripts/add-header-webcomponent.sh
- datahub/scripts/add-header.sh
I added this comments because it is already the second time I forgot to add +x and commit into the git
should be ported into docker-master as well
> add comment in the datahub header scripts

- gateway/application.yaml
Recovering the behavior we previously had with the security-proxy
> gateway - increasing session timeout to 24h

- datafeeder/datafeeder.properties
> [datafeeder] fix geoserver.api-url (fixes #365)

- cas/config/cas.properties
fixes georchestra/georchestra-cas-server#21
> backport 0f42391db to master to fix cas

- mapstore/configs/localConfig.json
trying as much as possible to keep https://github.com/georchestra/mapstore2-georchestra/blob/master/configs/localConfig.json & https://github.com/georchestra/datadir/blob/master/mapstore/configs/localConfig.json in sync..
> [mapstore] backport georchestra/mapstore2-georchestra#663

- default.properties
Missing bits from https://github.com/georchestra/georchestra/pull/4047
> add missing enableRabbitmqEvents

- default.properties
- mapstore/configs/localConfig.json
Main PR :
- https://github.com/georchestra/georchestra/pull/4120
This PR adds missing 'logo-url' attribute and new 'stylesheet' attribute
> Themable Webcomponent header

- console/templates/new-oauth2-account-notification-template.txt
- console/templates/newaccount-notification-template.txt
A new email template for OAuth2 account creation is added.
> Adding new email template when creating new OAuth2 account

- datafeeder/datafeeder.properties
Add configurable store name and workspace name for geoserver
> Geoserver Storename and worspacename

- cas/config/cas.properties
Following https://github.com/georchestra/georchestra-cas-server/pull/25 we now need these to make sure cas is able to run.
> cas - adding default properties for saml provider to work

- gateway/gateway.yaml
- security-proxy/security-mappings.xml
This PR allows only IMPORT and SUPERUSER roles to datafeeder / import routes.
Depends on main PR : 
- https://github.com/georchestra/georchestra/pull/4190
> Implement IMPORT role to datafeeder / import routes

- gateway/README.md
Need [PR#138 of gateway](https://github.com/georchestra/georchestra-gateway/pull/138) to be complete.
> Added documentation for gateway configuration files

- gateway/gateway.yaml
- security-proxy/security-mappings.xml
Should also be backported to docker-24.0 branch
> fix: apply changes from PR #390 to docker-master branch

- data-api/application.yaml
- gateway/routes.yaml
> Add data-api

- datahub/conf/default.toml
update with this file : https://github.com/geonetwork/geonetwork-ui/blob/main/conf/default.toml
> update datahub config from upstream

- gaia/celeryconfig.py
- gaia/config.py
- gaia/gunicorn.conf.py
this is the default configuration coming from https://github.com/georchestra/gaia
> Add gaia config docker
