- ldapadmin/ldapadmin.properties
publicContextPath should be the same as shared.ldapadmin.contextpath, see https://github.com/georchestra/georchestra/blob/15.06/config/shared.maven.filters#L61
> ldapadmin contextpath normalized

- security-proxy/security-mappings.xml
because it is used by account creation form
> security-proxy - allow access to org map configuration to anonymous

- analytics/log4j/log4j.properties
- catalogapp/log4j/log4j.properties
- downloadform/log4j/log4j.properties
- extractorapp/log4j/log4j.properties
- geowebcache/log4j/log4j.properties
- header/log4j/log4j.properties
- ldapadmin/log4j/log4j.properties
- mapfishapp/log4j/log4j.properties
- security-proxy/log4j/log4j.properties
This PR:
* replaces remaining `RollingFileAppender` with `ConsoleAppender` where applicable
* replaces the `R` appender with `S` (for console) 
* normalizes logger names, eg `log4j.logger.catalogapp` -> `log4j.logger.org.georchestra.catalogapp`
To be cascade-merged into the `docker-master` branch after acceptance.
Please review.
> console appenders everywhere with docker

- cas/cas.properties
- security-proxy/security-proxy.properties
Since [Traefik](https://traefik.io/) is used as frontend, we should instruct containers to use a FQDN rather than `localhost:8080`.
> setting a fqdn to the reverse-proxy

- security-proxy/headers-mapping.properties
This header will be added in LdapUserDetailsRequestHeaderProvider with the human
readable name of org from ou=orgs objects.
> security-proxy - Remove sec-orgname header

- security-proxy/security-mappings.xml
After the https://github.com/georchestra/georchestra/pull/1902 merge, the CAS entrypoint for validating tickets changed ; containing a 'login' in the redirect URL, there was an infinite loop while clicking on the login link in the header.
Note: to be merged into docker-master.
> SP - fix cas behind SP

- geonetwork/geonetwork.properties
Following previous PR, these 2 variables are missing relying on the config-security-georchestra xml file.
Tests: tested directly on GGE
> GN - fixing missing properties

- mapfishapp/js/GEOR_custom.js
After https://github.com/georchestra/georchestra/pull/2066
> mapfishapp - remove deprecated HEADER_HEIGHT in js config

- mapfishapp/wmts.servers.json
Note that we need to add the fqdn to `removed-xforwarded-headers.properties` for it to work fine, the remote mapproxy behaves weird.. probably a badly configured reverse proxy on the remote side.
@ndamiens are you fine with that ? @bchartier, an opinion ? That would allow to provide an alternative to the poor overloaded osm.geobretagne.fr, i think @fphg will like it :)
> Add osm.geopicardie.fr service to the list of default available wmts servers

- security-proxy/security-proxy.properties
The property files will no more be filtered, so they cannot contain
placeholders (`${...}`).
See https://github.com/georchestra/georchestra/issues/1417.
> security-proxy - remove dependency to configjar

- cas/cas.properties
The property files will no more be filtered, so they cannot contain
placeholders (`${...}`).
See https://github.com/georchestra/georchestra/issues/1417.
> cas - remove dependency to configjar

- atlas/atlas.properties
The property files will no more be filtered, so they cannot contain
placeholders (${...}).
See https://github.com/georchestra/georchestra/issues/1417.
> atlas - remove dependency to configjar

- README.md
Replaces https://github.com/georchestra/datadir/pull/101.
But maybe it's anecdotal and useless...
> doc - georchestra.datadir is optional with mvn jetty:run

- default.properties
- geowebcache/geowebcache.properties
Also comment by default the property for geowebcache as it is already for the other modules (except mapfishapp).
And add comments in default.properties.
See https://github.com/georchestra/georchestra/pull/2368.
> Harmonize headerHeight property name

- console/console.properties
`roleUniqueNumberField` and `accountUniqueNumberField` do not seem to be in use by the console code on master
> console - remove unused properties

- analytics/analytics.properties
- atlas/atlas.properties
- console/console.properties
- extractorapp/extractorapp.properties
- mapfishapp/mapfishapp.properties
- security-proxy/log4j/log4j.properties
- security-proxy/security-proxy.properties
All apps that connect to Postgres through JDBC now
have a unified way of configuring the DataSource
as a connection pool.
This patch sets the default values for these configurable
properties on each app .properties file.
> Add configuration for connection pool dimensioning

- geoserver/s3-geotiff/s3-geotiff-ehcache.xml
- geoserver/s3-geotiff/s3.properties
Add the s3-geotiff cache and server aliases configuration files to geoserver's georchestra datadir.
They aren't mandatory, but the cache configuration file has better defaults for an actual deployment than the `gt-s3-geotiff` hardcoded defaults.
> GeoServer configuration for S3 GeoTiff module

- analytics/analytics.properties
- atlas/atlas.properties
- cas/cas.properties
- console/console.properties
- default.properties
- extractorapp/extractorapp.properties
- geowebcache/geowebcache.properties
- header/header.properties
- mapfishapp/mapfishapp.properties
- security-proxy/security-proxy.properties
Since a default value is set in the geOrchestra code when any property
is loaded from a properties file, it's not necessary to provide it also
in the datadir properties files, unless it is different from the default.
It also makes it easier for the instance administrator to review their
datadir, focusing only on important properties, and letting the default
values unchanged for the rest of the properties.
See https://github.com/georchestra/datadir/issues/129 for the
motivation.
Note that the default.properties file has been let uncommented, as we
always want these values to be set by the instance administrator.
> Comment (nearly) all properties in properties files

- analytics/analytics.properties
instead of setting different properties suffixed with a different
number.
> Use the comma-separated list format to configure the excluded users

- analytics/analytics.properties
- atlas/atlas.properties
- cas/cas.properties
- console/console.properties
- console/templates/account-uid-renamed.txt
- default.properties
- extractorapp/extractorapp.properties
- geowebcache/geowebcache.properties
- header/header.properties
- mapfishapp/mapfishapp.properties
- security-proxy/security-proxy.properties
The properties from the default.properties file are used inside the
applications properties files. In geOrchestra the default.properties
file is always loaded before the application properties files, so the
default values are available to these as placeholders.
> Use placeholders in properties files to reduce redundancy

- geonetwork/config/config-security-georchestra.xml
- geonetwork/geonetwork.properties
A proposal for https://github.com/georchestra/georchestra/issues/1682
This should be the default in geOrchestra IMO, now that we have true Orgs: no need to depend anymore on EL_* roles.
If accepted, this should be documented in the release + migration notes
> GeoNetwork groups now synced with LDAP Orgs

- security-proxy/security-proxy.properties
Indicates whether to allow semicolons in URLs to avoid erros like:
the request was rejected because the URL contained a potentially malicious String ";"
> security-proxy: Add allowSemicolon boolean property

- geonetwork/config/config-security-georchestra.xml
- geonetwork/geonetwork.properties
Fixes https://github.com/georchestra/georchestra/issues/2673 regression that was introduced by #62 
(thanks @cmangeat for pointing the issue with https://github.com/georchestra/datadir/commit/719aaad031e1be9db9f82a915d3f45774231b0da#r34587672)
GeoNetwork properties naming is a nightmare ...
> Fix GeoNetwork Org synchronization

- security-proxy/security-mappings.xml
Following the work on GDPR adding two extra services routed with the /console/account base path, security mappings need to be updated.
We need to have these services accessible for `IS_AUTHENTICATED_FULLY`
* /console/account/userdetails
* /console/account/changePassword
* /console/account/gdpr/download
* /console/account/gdpr/delete
And for `IS_AUTHENTICATED_ANONYMOUSLY`:
* /console/account/new
* /console/account/passwordRecovery
Hence the highest priority rule restricting access to `/console/account/.*` to  `IS_AUTHENTICATED_FULLY`
It's just unfortunate that public CSS and JS files are in the same path... see https://github.com/georchestra/georchestra/issues/2664 for improvements.
> proxy - inverting the logic to filter access to /console/account/*

- console/console.properties
Added minor changes in the Areas part (URL with added request SRS parameter and comment about AreasValue parameter).
In order to use proper encoding :
1) georchestra/datadir forked, cloned locally.
2) file console.properties loaded with proper encoding (ISO-8859-1) in Visual Studio code editor (I could see the file encoding in the status bar of VSC)
3) file saved and commited to my fork, then PR created from my fork
> Areas : minor changes

- console/console.properties
Goes in tandem with https://github.com/georchestra/georchestra/pull/2861 to fix  https://github.com/georchestra/georchestra/issues/2487
Add default ldap connection pool settings to `console.properties`
> console: add default LDAP connection pool settings

- mapstore/geostore.properties
As requested in https://github.com/georchestra/mapstore2-georchestra/issues/229.
Properties that can be overridden for mapstore (related to what is generally configured in default.properties) have been added to mapstore geostore.properties file.
> Added commented overridable mapstore properties in geostore.properties

- mapfishapp/addons/extractor/config.json
Starting from geOrchestra 20.0.6, addons' `config.json` file may override i18n strings, which is especially handy for the extractor addon admin to customize the help text/link.
> extractor addon - customizable i18n strings

- security-proxy/security-mappings.xml
Adding a rule for requesting through proxy.
Improving rule on login to match only urls with '/login', '/?login', '&login'
> proxy security mappings : rules on 'proxy' and 'login'

- datafeeder/datafeeder.properties
- security-proxy/headers-mapping.properties
- Document support for per-service headers
- Document support for base64 header encoding
- Document support for exentended organization and
manager headers
- Document all valid LDAP properties available to set
up request headers
- Add datafeeder specific header mappings
> Document support for extended header management

- datafeeder/datafeeder.properties
Add basic and headers auth config properties.
Use externalized configuration to set up authentication for both the
GeoServer and GeoNetwork REST clients, using the following configuration
in `datafeeder.properties`:
```
datafeeder.publishing.geoserver.auth.type=basic|headers
datafeeder.publishing.geoserver.auth.basic.username=<username>
datafeeder.publishing.geoserver.auth.basic.password=<pwd>
datafeeder.publishing.geoserver.auth.headers.[<header-name>]=<header-value>
datafeeder.publishing.geonetwork.auth.type=basic|headers
datafeeder.publishing.geonetwork.auth.basic.username=<username>
datafeeder.publishing.geonetwork.auth.basic.password=<pwd>
datafeeder.publishing.geonetwork.auth.headers.[<header-name>]=<header-value>
```
> [datafeeder] Externalize auth config of geoserver and geonetwork REST clients

- datafeeder/datafeeder.properties
- datafeeder/frontend-config.json
- datafeeder/metadata_template.xml
- datafeeder/metadata_transform.xsl
- datafeeder/templates/README.md
- datafeeder/templates/analysis-failed-email-template.txt
- datafeeder/templates/analysis-started-email-template.txt
- datafeeder/templates/data-publishing-failed-email-template.txt
- datafeeder/templates/data-publishing-succeeded-email-template.txt
- security-proxy/headers-mapping.properties
- security-proxy/security-mappings.xml
- security-proxy/targets-mapping.properties
The original workflow would be to modify the master branch first prior to merge into docker-master, but since the docker branch was used for the development, we now need to take back the current state of docker-master into master.
Tests: untested yet.
Note: datafeeder is configured to send its logs to stdout / stderr, it's up to the administrator who will deploy it to configure systemd or anything else the appropriate way, e.g. using the following directives in a potential service unit file:
```
StandardOutput=append:/var/log/wherever/mylogs.log
StandardError=append:/var/log/wherever/mylogs.log
```
Managing systemd services isn't probably into this repository's scope.
> Backport datafeeder configuration to master

- mapstore/configs/localConfig.json
merges https://github.com/georchestra/mapstore2-georchestra/commit/7279757e2f8272a26e0914a7f52cfbb7fb07e4a0#diff-ce67019ec67a33a6f40d0cdc3c72861c85f2a7701ac0d61080d8ff7e80ee9db7
and https://github.com/georchestra/mapstore2-georchestra/commit/b6dcdf46dff586dc9e831e6a68aedb0834085f40#diff-ce67019ec67a33a6f40d0cdc3c72861c85f2a7701ac0d61080d8ff7e80ee9db7
while retaining 2414fe65 (georchestra/mapstore2-georchestra#410 is still pending)
the only customization is pointing at `localgs` for `selectedService` in `DashboardEditor` .. and im not sure keeping the `Home` and `Language` plugins makes sense but thats my POV.
cf georchestra/mapstore2-georchestra#437 & georchestra/mapstore2-georchestra#438
> [mapstore] update localConfig.json for dashboards/geostories/homepage integration

- datafeeder/datafeeder.properties
- datafeeder/metadata_transform.xsl
fix georchestra/georchestra#3627
The resourceType was not taken from the template, but rather hardcoded to `series`.
( I did some test in my local fork of georchestra/georchestra 
https://github.com/jmbourdaret/georchestra/blob/727bdda7d26e9990613cbd0a4240165a85eb3bca/datafeeder/src/test/java/org/georchestra/datafeeder/service/publish/impl/GeorchestraTemplateMapperTest.java#L136
But as it does not involves any new code, and more importantly is based on copy of templates which are not synchronized with the ones used in the datadir; It is not relevant to push this test to geor/geor. )
> make resourceType dynamic

- cas/config/cas.properties
- cas/config/log4j2.xml
- datafeeder/datafeeder.properties
- datafeeder/templates/analysis-started-email-template.txt
the DF expected the $scheme property to be defined, which isn't since https://github.com/georchestra/datadir/pull/234
* disable default cas fixed credential list (casuser/Mellon). This is not so critical, as even if the authentication will succeed, then the authorization onto the SP (looking up the user from the LDAP to get the roles / orgs ...) won't work, and a 401 will be returned
* removing unused appenders from the log4j2 configuration
> Several fixes to the default docker config

- mapstore/printing/config.yaml
mostly to merge geosolutions-it/MapStore2@4b267214d6
but also realignes with upstream config, instead of copying the one from mfapp?
- use 'fixed' scales as that's what end users constantly complain about
- use an inline data: url for brokenUrlPlaceholder
- ditch the section about basic auth, no opinion on that one
- all the other changes are whitespace fixes coming from upstream ms2
> [mapstore] update printing config

- mapstore/configs/localConfig.json
The PR adds the following plugins to the "burger" menu:
- "Share"
- "MetadataExplorer" => allows adding layers in mobile mode (which surprisingly does not seem possible for now)
- ~~"Measure" => the angle measuring seems to have a bug on mobile, we should perhaps not add it for now~~
- "MapImport"
- "MapExport"
and button at the bottom right:
- "GlobeViewSwitcher" => allows switching to 3D
Only tested in devtools so far, not on real phone.
> Mapstore: Add more plugins to mobile mode

- security-proxy/security-mappings.xml
Makes an unauthenticated call to `/console/account/areaofcompetence` return a 404 instead of redirecting to the login page.
Complements https://github.com/georchestra/georchestra/pull/3869
> security-proxy: require logged-in user for /console/account/areaofcompetence

- geonetwork/geonetwork.properties
Otherwise the index config will be persisted in an external datadir and won't be updated automatically when upgrading GeoNetwork.
> Store GeoNetwork index config embedded inside the webapp

- geonetwork/geonetwork.properties
This setting uses the `geonetwork.config.dir` variable, so that if someone makes this variable point to the embedded files in the webapp, this will also work for the index config.
Followup of https://github.com/georchestra/datadir/pull/259
> Add a setting for the GeoNetwork index config path

- security-proxy/targets-mapping.properties
Targeting only `docker-master` because datahub is integrated in the docker composition only
> proxy - add mapping for datahub

- mapstore/configs/config.json
- mapstore/configs/localConfig.json
- mapstore/configs/new.json
the only 'behavioural' change is disabling `zoomToLayer` in `MetadataExplorer` plugin, which avoids zooming back to the layer extent when adding a layer - a silly behaviour, discussed with @catmorales & @lecault.
> [mapstore] update default configurations for 2022.02

- security-proxy/cookie-mappings.json
required for favourite metadata feature to work in datahub
cf georchestra/georchestra#3851
> [sec-proxy] add missing cookie-mappings.json file

- mapstore/configs/localConfig.json
lightly tested, `/mapstore/proxy` looks slightly broken (cf https://demo.georchestra.org/mapstore/proxy/?url=https%3A%2F%2Fwms-v.geopf.fr%2Fgeoserver%2Fows%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities  but thats unrelated to this change)
https://wms-v.geopf.fr & https://wfs.geopf.fr use geoserver, thus refuse to work if added to `useCors` array `(Reason: CORS Missing Allow Origin)`. using the mapstore proxy seems mandatory for those.
raster, tms & wmts seems to work.
will push to https://github.com/georchestra/mapstore2-georchestra/blob/master/configs/localConfig.json too
closes #307
> add beta urls for geoplateforme ogc sources (#307)

- geonetwork/microservices/ogc-api-records/config.yml
on ogc-api-records
Also force by default a maximum amount of connections in ogc-api-records
> Pre-expose parameters for hikari pooling

- datafeeder/metadata_transform.xsl
The change proposed by #315 for the datafeeder (choosing metadata language through metadata template manual editing) will work only if this is commented out.
> datafeeder - don't override language set in the MD template with eng

- datahub/README.md
- datahub/add-header-webcomponent.sh
- datahub/add-header.sh
This is heavily inspired from the work done for Géo2france.
Note that the `add-header-webcomponent.sh` script will inject the "new" header based on https://github.com/georchestra/header
This might only work with the geOrchestra gateway
> Datahub / add header injection & document customizations

- datahub/scripts/add-header.sh
@jeanmi151 That should work better for a vanilla geOrchestra installation!
> Fix default header url in the datahub add-header script

- gateway/routes.yaml
after merging need to be ported to docker-master
> adding cookie affinity in gateway config for geonetowrk/datahub

- datafeeder/metadata_transform.xsl
`metadataLanguage` is currently set "eng", which does not make sense for all setups.
Rather trust the provided template than overwrite with 'eng'.
> datafeeder - use template value for metadataLanguage

- datafeeder/frontend-config.json
- datafeeder/metadata_template.xml
- datafeeder/metadata_transform.xsl
We should use the `envsubst` service (https://github.com/georchestra/docker/blob/fe09e0aa2afd0259627c74f75a7bb356050cd335/docker-compose.yml#L33C3-L44) to have template URLs pointing at the instance fqdn by default.
> datafeeder - variabilize fqdn

- gateway/gateway.yaml
Runtime tested on the MEL platform, been able to load a dataset using the DF afterwards.
> gateway - DataFeeder expects the JSON versions of the http headers

- gateway/security.yaml
When authenticating from OAuth2 using the gateway, we need to create a local account if there is none. So we need admin credentials to LDAP.
> Added LDAP admin credentials for OAuth2 account creation

- datafeeder/datafeeder.properties
the key of the modified line was wrong if we follow the config schema from here : https://github.com/georchestra/georchestra/blob/master/datafeeder/src/main/resources/application.yml#L152
and here: https://github.com/georchestra/georchestra/blob/master/datafeeder/src/test/resources/datadir/datafeeder/datafeeder.properties#L87C1-L87C43
maybe the value should also be modified if we want to be aligned with previous links
> correcting key value in datafeeder configuration

- mapstore/configs/config.json
- mapstore/configs/localConfig.json
fixes #346 and removes the services that will disappear in a month, cf https://geoservices.ign.fr/bascule-vers-la-geoplateforme
probably needs backport to stable branches
> drop soon-to-be deprecated wxs.ign.fr and update default map

- datahub/conf/default.toml
Solves datahub searching only in french. 
Needs to be backported to master.
> fix #361: set datahub lang to all

- datahub/conf/default.toml
Upstream config is https://github.com/geonetwork/geonetwork-ui/blob/main/conf/default.toml
Direct benefit is everyone using docker images will get the "web component embedder" for free (see eg https://github.com/geonetwork/geonetwork-ui/blob/92348fa95cb211e2076d1374d862f883679ee0fe/tools/docker/Dockerfile.apps#L18), which allows to share the dataviz with a dedicated URL.
> Sync datahub config with upstream's

- default.properties
by default rabbitmq should not be enable as it is useless (for now) and not supported officially
connected with : https://github.com/georchestra/docker/pull/262
> disable rabbitmq by default

- mapstore/configs/localConfig.json
all formats are already enabled in mapfish-print cf https://github.com/georchestra/datadir/blob/master/mapstore/printing/config.yaml#L31
> [mapstore] enable PNG and JPG print output formats

- .backport/config.json
- .github/workflows/backport.yml
- gateway/gateway.yaml
Add a custom logoutUrl for gateway.
Also implment backport-bot. E.g : add label `backport-to-docker-master`
To be backport in `docker-master`
> Add logoutUrl to gateway.yaml

- cas/config/cas.properties
Following https://github.com/georchestra/georchestra-cas-server/pull/25 we now need these to make sure cas is able to run.
Same as #387, but targeting `docker-master`.
> cas - adding default properties for saml provider to work

- gateway/application.yaml
- gateway/routes.yaml
Solves problem with redirections and geoserver proxyBaseUrl. 
https://github.com/georchestra/georchestra/blob/master/docs/setup/tomcat.md#in-case-of-troubles-with-the-geoserver-ui
See :
- https://github.com/georchestra/helm-georchestra/pull/60
- https://github.com/georchestra/georchestra/blob/master/docs/setup/tomcat.md#in-case-of-troubles-with-the-geoserver-ui
- https://github.com/georchestra/georchestra-gateway/pull/104
> Update gateway config

- cas/config/cas.properties
to be merged if/when georchestra/georchestra-cas-server#13 is merged
> [cas] update config keys for cas 6.6 

- datahub/conf/default.toml
- default.properties
- gateway/routes.yaml
For gateway and 24, redirect to datahub and not legacy header and don't execute call to areaofcompetence 
Also disable analytics
> Redirect to datahub and not header and dont call areaofcompetence

- console/console.properties
Added parameter for email sent when email address change is requested.
See [console PR#4208](https://github.com/georchestra/georchestra/pull/4208)
> console - fixed missing email subject on user email changed

- console/console.properties
Parameters for consent checkbox on account creation
See [console PR#4239](https://github.com/georchestra/georchestra/pull/4239)
> feat: consent checkbox parameters

- geonetwork/log4j/log4j2.xml
this way we cant see errors and warnings when sync fails... otherwise the errors are just silently dropped.
witnessed on demo.geor where we didnt understand why sync wasnt working, those messages were not logged....
```
2024-06-27T09:15:52,763 WARN  [org.geonetwork.security.external.integration] - Synchronization failed, retrying in 10 SECONDS.
org.springframework.dao.InvalidDataAccessApiUsageException: The given id must not be null!; nested exception is java.lang.IllegalArgumentException: The given id must not be null!
```
needs backport to 24.0 branch
> add a logger config for org.geonetwork.security.external.integration

- cas/services/georchestra-1001.json
strongly advised by upstream since 6.6, cf https://apereo.github.io/cas/6.6.x/release_notes/RC3.html#cas-registered-services
with that, i don't have 
```
2024-06-27 00:17:07,363 WARN [org.apereo.cas.services.RegexRegisteredService] - <CAS has located a service definition type that is now tagged as [RegexRegisteredService]. This registered service definition type is scheduled for removal and should no longer be used for CAS-enabled applications, and MUST be replaced with [org.apereo.cas.services.CasRegisteredService] instead. We STRONGLY advise that you update your service definitions and make the replacement to facilitate future CAS upgrades.>
```
every minute in the logfile (cf #410), and cas login still works.
> [cas] use CasRegisteredService instead of RegexRegisteredService

- cas/config/log4j2.xml
because having 24 files a day, filled with garbage every minute:
```
2024-06-27 00:15:07,361 WARN [org.apereo.cas.services.RegexRegisteredService] - <CAS has located a service definition type that is now tagged as [RegexRegisteredService]. This registered service definition type is scheduled for removal and should no longer be used for CAS-enabled applications, and MUST be replaced with [org.apereo.cas.services.CasRegisteredService] instead. We STRONGLY advise that you update your service definitions and make the replacement to facilitate future CAS upgrades.>
2024-06-27 00:16:07,362 WARN [org.apereo.cas.services.RegexRegisteredService] - <CAS has located a service definition type that is now tagged as [RegexRegisteredService]. This registered service definition type is scheduled for …
```
> [cas] one logfile a day is enough

- console/console.properties
cf  georchestra/georchestra#4189 & georchestra/georchestra#4168 .. and thinking about it i wonder if it'd be better to move those to `default.properties` but that's more work in the xml config goo for both geonetwork and console.
> [console] add commented out parameters for georchestra/georchestra#4189

- gateway/application.yaml
- gateway/security.yaml
Configuration required for this gateway change:
https://github.com/georchestra/georchestra-gateway/pull/133
This patch adds the `LoginParamRedirect` default filter to the gateway.
Note the filter is added by default in the embedded `application.yml`, but since `gateway/application.yaml` is overriding the `spring.cloud.gateway.default-filters` list, it must be added here too.
> Use a GatewayFilter to redirect to the login page when given a login query parameter

- gateway/application.yaml
Set back to the default values of default-filters
There is no need to define only some of them, all the default-filters are useful. Some of them are useful because they fix some logic about /?login=, see https://github.com/georchestra/georchestra-gateway/pull/133
> set back to the default default-filters

- mapstore/proxy.properties
To mention targeted host instead of requesting hosts: 
See code here : https://github.com/geosolutions-it/http-proxy/blob/master/src/main/java/it/geosolutions/httpproxy/ProxyConfig.java#L44
> Update proxy comment

- console/console.properties
Allows to display organization's members list in `/console/account/userdetails`
> console - adding gdpr.displayMembersList

- mapstore/configs/localConfig.json
- mapstore/printing/config.yaml
This PR updates print config that aligns with latest MS stable 2024.02.xx
> Print config updated

- README.md
- default.properties
- gateway/security.yaml
- geonetwork/microservices/ogc-api-records/config.yml
Traefik.me availability seems flaky. I would propose to migrate to https://nip.io which has been in service for way longer and is really reliable, at least everytime I have used it was available. nip.io exists since 2012, whereas traefik.me only since 2019
> Move away from traefik.me

- datafeeder/inspire/topic_category-19115-3.xsl
- datafeeder/inspire/topic_category.xsl
- datafeeder/metadata_template-19115-3.xml
- datafeeder/metadata_template.xml
- datafeeder/metadata_transform-19115-3.xsl
- datafeeder/metadata_transform.xsl
To be backport on docker master after changing urls in  template with ${FQDN}.
> Set datafeeder template on 19115-3 standard

- geonetwork/microservices/ogc-api-records/config.yml
default the f=json output to geojson, add f=gnindex for the ones relying on the ES output format. from geonetwork/geonetwork-microservices#119
adds /conformance, from  geonetwork/geonetwork-microservices#59
with that, GN 4.4.5 and the ogc-api-records microservice from [4.4.6-1](https://github.com/geonetwork/geonetwork-microservices/releases/tag/4.4.6-1) deployed on demo.geor, we have:
- https://demo.georchestra.org/ogc-api-records/collections/main/items?limit=10&f=json returning the same as `f=geojson`
- https://demo.georchestra.org/ogc-api-records/collections/main/items?limit=10&f=gnindex returns what was previously the default for `f=json`
- https://demo.georchestra.org/ogc-api-records/collections/main/items?limit=10&f=rss gives a working RSS feed.
> update gn-ogc-api-records default config for 4.4.6-1

- console/console.properties
It's better to have it next to the relevant options
> console - relocate the competenceAreaEnabled option

- gateway/routes.yaml
Add default value for each gw services with an "**HOST" variable.
Also fixes the helm chart geOrchestra because the environment variable `DATA_API_HOST` does not exist in the helm chart.
And this allows anybody to disable some services and still have a working gateway. Since the GW will fail if it can't resolve all the environment variables.
> chore: default variables for environment variables

- datahub/conf/default.toml
- gateway/routes.yaml
Used to avoid preflight request being forbid by gateway. 
Old problem: (in french) https://groups.google.com/g/georchestra-dev/c/PeXxK1Zz_8I?pli=1
and set proxy to mapstore's for datahub.
> Add cors to GW's gn route
